"use client";

import { useCallback, useRef, useState } from "react";
import { useRouter } from "next/navigation";

import { buttonClass } from "@/components/ui/button-styles";
import { SparkleIcon } from "@/components/ui/icons";
import { formatCount, formatDecimal } from "@/lib/format";
import type { PersistedEventForecast } from "@/server/organizers/queries";

/**
 * The one control that makes the AI service get called.
 *
 * Everything else about forecasting is deliberately not interactive: the dashboard
 * reads cached rows while rendering and never calls the AI service during a page
 * render (API_CONTRACT.md §7.1). This button is the explicit trigger from §7.4
 * step 4 — nothing runs on mount, on focus, or on an interval, so opening the page
 * with the service stopped still renders instantly.
 *
 * The component is a thin shell, in the same spirit as `CheckInConsole`: it posts to
 * the endpoint, reports the outcome in words, and lets the server decide everything.
 * On success it calls `router.refresh()` rather than holding a second copy of the
 * forecast in state, so the number an organizer reads comes from the same server
 * component and the same query as a normal page load — there is no client-side
 * version of the truth to drift.
 */

type RefreshState =
  | { kind: "idle" }
  | { kind: "refreshing" }
  | { kind: "refreshed"; forecast: PersistedEventForecast }
  | { kind: "failed"; message: string };

type ApiErrorBody = {
  error?: {
    code?: string;
    message?: string;
    request_id?: string;
  };
};

async function readErrorMessage(response: Response, fallback: string): Promise<string> {
  try {
    const body = (await response.json()) as ApiErrorBody;

    if (body.error?.message) {
      // The server already writes organizer-safe copy; the request id is the handle
      // for a bug report, which is how `CheckInConsole` reports failures too.
      return body.error.request_id
        ? `${body.error.message} (ref ${body.error.request_id})`
        : body.error.message;
    }
  } catch {
    // A non-JSON body is still an error; fall through to the fallback.
  }

  return fallback;
}

export function ForecastRefresh({
  eventId,
  hasForecast,
}: {
  eventId: string;
  /** Whether a cached forecast already exists, so the button can say the right thing. */
  hasForecast: boolean;
}) {
  const router = useRouter();
  const [state, setState] = useState<RefreshState>({ kind: "idle" });
  const inFlightRef = useRef(false);

  const isRefreshing = state.kind === "refreshing";

  const refresh = useCallback(async () => {
    // Guards the button against a second click landing while the first call is still
    // in flight, which would otherwise write two forecast rows for one intention.
    if (inFlightRef.current) {
      return;
    }

    inFlightRef.current = true;
    setState({ kind: "refreshing" });

    try {
      const response = await fetch(`/api/organizer/events/${encodeURIComponent(eventId)}/forecast`, {
        method: "POST",
        cache: "no-store",
      });

      if (!response.ok) {
        setState({
          kind: "failed",
          message: await readErrorMessage(
            response,
            "The forecast could not be refreshed. Try again.",
          ),
        });
        return;
      }

      const body = (await response.json()) as { forecast: PersistedEventForecast };

      setState({ kind: "refreshed", forecast: body.forecast });
      // Re-read the dashboard from the server so the newly cached forecast renders
      // through the same component tree as before.
      router.refresh();
    } catch {
      setState({
        kind: "failed",
        message:
          "Could not reach the app to refresh the forecast. Check the connection and try again.",
      });
    } finally {
      inFlightRef.current = false;
    }
  }, [eventId, router]);

  return (
    <section className="sponsor-banner relative flex flex-col gap-3 overflow-hidden rounded-card border border-white/80 p-5 shadow-card">
      <div className="pointer-events-none absolute -top-10 -right-8 size-28 rounded-full border border-white/55" />
      <div className="relative flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-start gap-3">
          <span className="grid size-11 shrink-0 place-items-center rounded-logo bg-upay-yellow text-upay-blue shadow-logo ring-4 ring-white/45">
            <SparkleIcon className="size-5" />
          </span>
          <div className="flex max-w-xl flex-col gap-1">
            <h2 className="text-sm font-extrabold text-upay-navy">Attendance forecast</h2>
            <p className="text-xs font-medium text-upay-navy/60">
              Generated by the AI service when you ask for it, then cached in the database. This
              page reads the cached forecast and never calls the AI service while rendering.
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={() => void refresh()}
          disabled={isRefreshing}
          aria-busy={isRefreshing}
          className={buttonClass("primary", "md")}
        >
          {isRefreshing ? "Refreshing…" : hasForecast ? "Refresh forecast" : "Generate forecast"}
        </button>
      </div>

      {/* Failures are announced assertively, progress and success politely — the same
          split `CheckInConsole`'s result banner uses. */}
      {state.kind === "failed" ? (
        <p role="alert" className="relative text-xs font-medium text-red-600">
          {state.message} Any forecast already cached for this event is unchanged.
        </p>
      ) : (
        <p role="status" aria-live="polite" className="relative text-xs font-medium text-upay-navy/60">
          {state.kind === "refreshing" ? "Asking the AI service for a fresh forecast…" : null}

          {state.kind === "refreshed"
            ? `Cached just now: ${formatDecimal(state.forecast.predictedAttendance)} predicted attendees out of ${formatCount(state.forecast.paidRegistrations)} paid registrations.`
            : null}
        </p>
      )}
    </section>
  );
}